# Generated by Django 6.0.3 on 2026-03-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_delete_appointments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
